version: '3.8'

services:
  portal_web:
    build: .
    container_name: ia_quant_portal
    command: streamlit run app_portal.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    restart: always

  robot_ia:
    build: .
    container_name: ia_quant_robot
    command: python robot_ejecutor.py
    restart: always
